## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique(axis=0)
unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ["T9", "T13", "T12", "T2", "T25", "T14", "T29", "T15", "T17"]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df["CLASSIFICATION"].value_counts()[application_df["CLASSIFICATION"].value_counts() > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_list = application_df['CLASSIFICATION'].unique().tolist()
classifications_to_replace = []

for id in class_list:
  if ((id != "C1000") & (id != "C2000") & (id != "C1200") & (id != "C3000") & (id != "C2100")):
    classifications_to_replace.append(id)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(data=application_df, columns=['CLASSIFICATION', 'APPLICATION_TYPE', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'])
merged = pd.concat([application_df, dummies], axis='columns')
merged = merged.drop(['CLASSIFICATION', 'APPLICATION_TYPE', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS'], axis='columns')
merged.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,STATUS,ASK_AMT,IS_SUCCESSFUL,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,CLASSIFICATION_C2100,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,5000,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,1,108590,1,0,0,1,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,1,5000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,1,6692,1,0,0,1,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,1,142590,1,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split the preprocessed data into a features array, X, and a target array, y.
# Use these arrays and the train_test_split function to split the data into training and testing datasets.

# Split our preprocessed data into our features and target arrays
y = merged["IS_SUCCESSFUL"]
X = merged.drop(columns=["IS_SUCCESSFUL"])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

# Increase the number of nodes
number_input_features = 45
hidden_nodes_layer1 = 120
hidden_nodes_layer2 = 60
hidden_nodes_layer3 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Add a third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=2, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 120)               5520

 dense_1 (Dense)             (None, 60)                7260

 dense_2 (Dense)             (None, 30)                1830

 dense_3 (Dense)             (None, 2)                 62

=================================================================
Total params: 14,672
Trainable params: 14,672
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Train the model
# Increase the number of epochs
fit_model = nn.fit(X_train_scaled,y_train,epochs=150)

Epoch 1/150
804/804 [==============================] - 9s 8ms/step - loss: 0.5682 - accuracy: 0.4850
Epoch 2/150
804/804 [==============================] - 5s 7ms/step - loss: 0.5533 - accuracy: 0.4909
Epoch 3/150
804/804 [==============================] - 6s 8ms/step - loss: 0.5500 - accuracy: 0.5042
Epoch 4/150
804/804 [==============================] - 5s 6ms/step - loss: 0.5488 - accuracy: 0.4816
Epoch 5/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.5248
Epoch 6/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.5115
Epoch 7/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.4753
Epoch 8/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5447 - accuracy: 0.4886
Epoch 9/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5437 - accuracy: 0.4883
Epoch 10/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.4965
Epoch 11/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.5192
Epoch 12/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.5040
Epoch 13/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.4757
Epoch 14/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5414 - accuracy: 0.4984
Epoch 15/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.4783
Epoch 16/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.5232
Epoch 17/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.4931
Epoch 18/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.4874
Epoch 19/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5396 - accuracy: 0.5190
Epoch 20/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5395 - accuracy: 0.4956
Epoch 21/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.5392
Epoch 22/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.5105
Epoch 23/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.5133
Epoch 24/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.4995
Epoch 25/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5381 - accuracy: 0.5058
Epoch 26/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.5323
Epoch 27/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5378 - accuracy: 0.5001
Epoch 28/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.5463
Epoch 29/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.5292
Epoch 30/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.5086
Epoch 31/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.5126
Epoch 32/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.5057
Epoch 33/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.5291
Epoch 34/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.5198
Epoch 35/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.4762
Epoch 36/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.5082
Epoch 37/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5358 - accuracy: 0.5135
Epoch 38/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5357 - accuracy: 0.5072
Epoch 39/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.4973
Epoch 40/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5353 - accuracy: 0.4640
Epoch 41/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.4628
Epoch 42/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.5012
Epoch 43/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.4622
Epoch 44/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.5185
Epoch 45/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5347 - accuracy: 0.5156
Epoch 46/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.5018
Epoch 47/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.5231
Epoch 48/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5348 - accuracy: 0.5157
Epoch 49/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.4543
Epoch 50/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.5034
Epoch 51/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.5455
Epoch 52/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.5132
Epoch 53/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.4389
Epoch 54/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.5004
Epoch 55/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.4929
Epoch 56/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.5311
Epoch 57/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.5046
Epoch 58/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.5321
Epoch 59/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.4763
Epoch 60/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5331 - accuracy: 0.4723
Epoch 61/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.4794
Epoch 62/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.5642
Epoch 63/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.4769
Epoch 64/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.5330
Epoch 65/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.5082
Epoch 66/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.5772
Epoch 67/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.5100
Epoch 68/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5325 - accuracy: 0.5389
Epoch 69/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5326 - accuracy: 0.5604
Epoch 70/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.5735
Epoch 71/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5319 - accuracy: 0.5950
Epoch 72/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.5664
Epoch 73/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5320 - accuracy: 0.5571
Epoch 74/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.5905
Epoch 75/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.5723
Epoch 76/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.5739
Epoch 77/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.6130
Epoch 78/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.6381
Epoch 79/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5312 - accuracy: 0.6118
Epoch 80/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.6184
Epoch 81/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5313 - accuracy: 0.6340
Epoch 82/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.5784
Epoch 83/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.5414
Epoch 84/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5310 - accuracy: 0.5592
Epoch 85/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.5405
Epoch 86/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5311 - accuracy: 0.5907
Epoch 87/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.5934
Epoch 88/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.5687
Epoch 89/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5312 - accuracy: 0.6002
Epoch 90/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5308 - accuracy: 0.5758
Epoch 91/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.6045
Epoch 92/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.5942
Epoch 93/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5309 - accuracy: 0.5908
Epoch 94/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5306 - accuracy: 0.6183
Epoch 95/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.6026
Epoch 96/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5306 - accuracy: 0.5844
Epoch 97/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5303 - accuracy: 0.6134
Epoch 98/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.5905
Epoch 99/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.5923
Epoch 100/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5312 - accuracy: 0.6009
Epoch 101/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5307 - accuracy: 0.5985
Epoch 102/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5305 - accuracy: 0.6265
Epoch 103/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5305 - accuracy: 0.6169
Epoch 104/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.5983
Epoch 105/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5304 - accuracy: 0.6067
Epoch 106/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.5526
Epoch 107/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5312 - accuracy: 0.6109
Epoch 108/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5304 - accuracy: 0.6264
Epoch 109/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.6143
Epoch 110/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.6362
Epoch 111/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.6628
Epoch 112/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.6539
Epoch 113/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.6624
Epoch 114/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5386 - accuracy: 0.6750
Epoch 115/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.6239
Epoch 116/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.5536
Epoch 117/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5296 - accuracy: 0.5678
Epoch 118/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5290 - accuracy: 0.5575
Epoch 119/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5299 - accuracy: 0.6022
Epoch 120/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5300 - accuracy: 0.6001
Epoch 121/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.5919
Epoch 122/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.5569
Epoch 123/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.5565
Epoch 124/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5301 - accuracy: 0.5731
Epoch 125/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5295 - accuracy: 0.6042
Epoch 126/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5295 - accuracy: 0.5617
Epoch 127/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.5763
Epoch 128/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.5978
Epoch 129/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.6213
Epoch 130/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.5814
Epoch 131/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5293 - accuracy: 0.6428
Epoch 132/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.6785
Epoch 133/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.6123
Epoch 134/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5294 - accuracy: 0.6104
Epoch 135/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.6352
Epoch 136/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5298 - accuracy: 0.6782
Epoch 137/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5294 - accuracy: 0.5793
Epoch 138/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5318 - accuracy: 0.6679
Epoch 139/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.5631
Epoch 140/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.5980
Epoch 141/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5294 - accuracy: 0.7357
Epoch 142/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5290 - accuracy: 0.4737
Epoch 143/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5288 - accuracy: 0.6259
Epoch 144/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.6529
Epoch 145/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5287 - accuracy: 0.8108
Epoch 146/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7309
Epoch 147/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5290 - accuracy: 0.6263
Epoch 148/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.5248
Epoch 149/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5301 - accuracy: 0.4704
Epoch 150/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5291 - accuracy: 0.5136

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5790 - accuracy: 0.9195 - 755ms/epoch - 3ms/step
Loss: 0.5789865851402283, Accuracy: 0.9195335507392883

In [17]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")